# from constant.messages import CLUB_NAME_NOT_MATCH, TITLE_NAME_NOT_MATCH, CONTACT_FIELD_ERROR_MESSAGE, \
#     EMAIL_FIELD_ERROR_MESSAGE, PAGE_NAME_NOT_MATCH, ERROR_MESSAGE_NOT_MATCH, EMAIL_REQUIRED, \
#     MESSAGE_NOT_MATCHED,  BUTTON_NAME_NOT_MATCH
#
# __all__ = [
#     "CLUB_NAME_NOT_MATCH", "TITLE_NAME_NOT_MATCH", "CONTACT_FIELD_ERROR_MESSAGE", "EMAIL_FIELD_ERROR_MESSAGE",
#     "PAGE_NAME_NOT_MATCH", "ERROR_MESSAGE_NOT_MATCH", "EMAIL_REQUIRED", "MESSAGE_NOT_MATCHED",
#     "BUTTON_NAME_NOT_MATCH"
# ]
