BASEURL = 'https://demo.opencart.com.gr/'
EMAIL = 'test@yopmail.com'
PASSWORD ='1234'
FIRSTNAME = "prem"
LASTNAME = "wer"
PHONE = "9898989898"
EXISTING_EMAIL = "test@yopmail.com"
INCORRECT_FIRSTNAME = "a"
INCORRECT_LASTNAME = "b"
INCORRECT_EMAIL = "b123GMAIL"
INCORRECT_MOBILE = "12"
INCORRECT_PASSWORD = "wer12345"
INCORRECT_CONFIRM_PASSWORD = "wer123"
# EMAIL_ID = "aqw07@gmail.com"
# VERIFIED_EMAIL = "pot@mailinator.com"
# CHANGE_MOBILE = "9111112222"
# INVALID_CURRENT_PRICE = "e34r"
# VALID_CURRENT_PRICE = "79.9101"
# VALID_STRIKE_PRICE = "82"
# STOCK_SPOT_PRICE = "56"
# DIVIDEND_PRICE = "96"
# INVALID_PRICE = "0"
# INVALID_DECIMAL_VALUE = "5..2"
# MY_PROFILE_PHONE = "9214563784"



